project:
  type: website

website:
  title: "quarto"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: quarto.qmd
        text: Quarto
      - href: git.qmd
        text: Git
      - href: about.qmd
        text: About


format:
  html:
    embed-resources: true
    theme: default
    css: styles.css
    toc: true
    extensions:
      - mermaid
   
      



